# Generated by Django 5.2.8 on 2026-04-06 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_followers_likepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='no_of_like',
            new_name='no_of_likes',
        ),
    ]
